name: Deploy MkDocs to Public Repo

on:
  push:
    branches:
      - main # or your default branch
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install MkDocs
        run: |
          pip install mkdocs mkdocs-material "mkdocstrings[python]"

      - name: Build docs
        run: mkdocs build --clean --config-file docs/mkdocs.yml

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DOCS_DEPLOY_KEY_BIS }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Deploy to public repo
        run: |
          cd docs/site
          touch .nojekyll
          git init
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy docs"
          git branch -M main
          git remote add origin git@github.com:MEL-Eduwell-lab/deepepix-docs.git
          GIT_SSH_COMMAND="ssh -i ~/.ssh/deploy_key" git push -f origin main